apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-app
spec:
  selector:
    matchLabels:
      app: product-service-app
  template:
    metadata:
      labels:
        app: product-service-app
    spec:
      containers:
        - name: product-service-app
          image: balasabbineni97/product-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EurekaUrl
              valueFrom:
                configMapKeyRef:
                  key: eureka_url
                  name: eureka-cm
            - name: CONFIG_SERVER
              valueFrom:
                configMapKeyRef:
                  key: config_url
                  name: config-cm
            - name: DB_HOST
              valueFrom:
                  configMapKeyRef:
                    name: mysql-cm
                    key: hostname

---
apiVersion: v1
kind: Service
metadata:
  name: product-service-svc
spec:
  selector:
    app: product-service-app
  ports:
    - port: 80
      targetPort: 8080